[build.environment]
  # bypass npm auto install
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "build"
  command = "npm ci --force && npm run build"

[[redirects]]
  from = "/api/*"
  to = "http://gfibot.io:5000/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"