version: "2.2"

services:
  mongodb:
    image: mongo
    volumes:
      # - /data/heh/mongodb:/data/db
      - /data/hrz/gfi-data/mongodb:/data/db
    command: mongod --bind_ip=0.0.0.0 --port=27020
    ports:
      - "27020:27020"  # debug only
    mem_limit: 10G
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  gfi-bot:
    build:
      context: ../
      dockerfile: ./production/gfibot.dockerfile
    ports:
      - "5000:5000"  # debug only
    depends_on:
      - mongodb
    volumes:
      - /data/hrz/gfi-data/models:/models
    mem_limit: 10G
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  frontend:
    build:
      context: ../
      dockerfile: ./production/frontend.dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - /data/hrz/gfi-data/certs/:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/
    depends_on:
      - gfi-bot
