name: Test Docker Compose Pipeline

on:
  push:
    branches: [ "main", "my-first-fix" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Docker Compose Stack
      run: |
        docker compose up -d
        docker compose ps